Style.MethodCallParentheses:
  Enabled: false
  Description: Do not use parentheses for method calls with no arguments.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide

Style/MutableConstant:
  Enabled: false
  Description: Freeze mutable constants.

Style/GuardClause:
  Desription: Check for conditions that can be replaced with guard clauses.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide
  Enabled: false
  MinBodyLength: 1

Style/BracesAroundHashParameters:
  Enabled: false
  EnforcedStyle: no_braces
  SupportedStyles: 
  - braces
  - no_braces
  - context_dependent

Style/CommentAnnotation:
  Description: >-
    Checks formatting of special comments
    (TODO, FIXME, OPTIMIZE, HACK, REVIEW).
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide'
  Enabled: false

Style/StringLiterals:
  Enabled: false
  EnforcedStyle: single_quotes
  SupportedStyles:
  - single_quotes
  - double_quotes

Metrics/LineLength:
  Description: Limit lines to 80 characters.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide
  Enabled: true
  Max: 80
  AllowURI: true
  URISchemes:
  - http
  - https